maildev:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - maildev.chart-example.local

php:
  image:
    repository: bikelib-php
    tag: latest

caddy:
  image:
    repository: bikelib-caddy
    tag: latest

service:
  type: NodePort

external-dns:
  enabled: false