version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/api"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
    groups:
      symfony:
        patterns:
          - "symfony/*"

      api-platform:
        patterns:
          - "api-platform/*"


  - package-ecosystem: "npm"
    directory: "/pwa"
    commit-message:
        prefix: "chore"
    schedule:
        interval: "weekly"
    open-pull-requests-limit: 5


  - package-ecosystem: "helm"
    directory: "/helm"
    commit-message:
        prefix: "chore"
    schedule:
        interval: "weekly"
    open-pull-requests-limit: 5


  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
        prefix: "chore"
    schedule:
        interval: "weekly"
    open-pull-requests-limit: 5
