apiVersion: v1
kind: Service
metadata:
  name: {{ include "bikelib-pwa.fullname" . }}
  labels:
    {{- include "bikelib-pwa.labelsPWA" . | nindent 4 }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "bikelib-pwa.selectorLabelsPWA" . | nindent 4 }}
