version: '3.4'

services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./:/srv/app
#      - storage:/srv/app/public/storage
      - ./api/docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway

  caddy:
#    ports:
#      - '8009:80'
    volumes:
      - ./public:/srv/app/public:ro
#      - storage:/srv/app/public/storage
      - ./api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  database:
    ports:
      - '5432:5432'
