framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        headers:
            From: 'Rustine Libre <%env(MAILER_SENDER)%>'

when@test:
    framework:
        mailer:
            dsn: 'null://null'
