framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_SENDER)%'
        headers:
            From: '%env(MAILER_SENDER)%'

when@test:
    framework:
        mailer:
            dsn: 'null://null'
