framework:
    workflows:
        appointment_acceptance:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: method
                property: status
            supports:
                - App\Entity\Appointment
            initial_marking: pending_repairer
            places:
                - pending_repairer
                - validated
                - refused
                - cancel
            transitions:
                validated_by_repairer:
                    from: pending_repairer
                    to:   validated
                refused:
                    from: [pending_repairer]
                    to:   refused
                propose_another_slot:
                    from: [pending_repairer, validated]
                    to:   validated
                cancellation:
                    from: [pending_repairer, validated]
                    to:   cancel
