ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: toset
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: toset
      hosts:
        - toset

imagePullSecrets:
  - name: regcred

php:
  medias:
    persistence:
      storageClass: "standard"

caddy:
  image:
    repository: "ghcr.io/cooptilleuls/rustinelibre-caddypreprod"
