ingress:
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: toset
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: toset
      hosts:
        - toset

imagePullSecrets:
  - name: regcred

php:
  medias:
    persistence:
      storageClass: "standard"