imagePullSecrets:
  - name: regcred

ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: toset
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: toset
      hosts:
        - toset

postgresql:
  persistence:
    enabled: true
    storageClass: "regionalpd-sc-euwest1"
