apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bikelib.fullname" . }}
  labels:
    {{- include "bikelib.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "bikelib.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bikelib.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bikelib.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-caddy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.caddy.image.repository }}:{{ .Values.caddy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.caddy.image.pullPolicy }}
          env:
            - name: SERVER_NAME
              value: :80
            - name: PWA_UPSTREAM
              value: {{ include "bikelib.fullname" . }}-pwa:3000
            - name: MERCURE_EXTRA_DIRECTIVES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mercure-extra-directives
            - name: MERCURE_PUBLISHER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mercure-jwt-secret
            - name: MERCURE_SUBSCRIBER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mercure-jwt-secret
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: admin
              containerPort: 2019
              protocol: TCP
          volumeMounts:
            {{- if .Values.php.medias.persistence.enabled }}
            - mountPath: /srv/app/public/media
              name: php-medias
            {{- end }}          
            - mountPath: /var/run/php
              name: php-socket
          lifecycle:
            preStop:
              exec:
                command: ["curl", "-XPOST", "http://localhost:2019/stop"]
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources.caddy | nindent 12 }}
        - name: {{ .Chart.Name }}-php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          env:
            - name: API_ENTRYPOINT_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-host
            - name: JWT_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-jwt-passphrase
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-jwt-public-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-jwt-secret-key
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-trusted-proxies
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-app-env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-app-debug
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-app-secret
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-cors-allow-origin
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: database-url
            - name: MAILER_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mailer-dsn
            - name: MERCURE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mercure-url
            - name: MERCURE_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mercure-public-url
            - name: MERCURE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mercure-jwt-secret
            - name: STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "plateformcoop-ebs" . }}
                  key: php-storage-bucket
            - name: STORAGE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "plateformcoop-ebs" . }}
                  key: php-storage-endpoint
            - name: STORAGE_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "plateformcoop-ebs" . }}
                  key: php-storage-region
            - name: STORAGE_USE_PATH_STYLE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "plateformcoop-ebs" . }}
                  key: php-storage-use-path-style-endpoint
            - name: STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "plateformcoop-ebs" . }}
                  key: php-storage-key
            - name: STORAGE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "plateformcoop-ebs" . }}
                  key: php-storage-secret
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: firebase-project-id
            - name: FIREBASE_PRIVATE_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: firebase-private-key-id
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: firebase-private-key
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: firebase-client-email
            - name: FIREBASE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: firebase-client-id
            - name: FIREBASE_AUTH_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: firebase-auth-uri
            - name: FIREBASE_TOKEN_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: firebase-token-uri
            - name: FIREBASE_AUTH_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: firebase-auth-provider
            - name: FIREBASE_CLIENT_CERT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: firebase-client-cert-url
            - name: FIREBASE_UNIVERSE_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: firebase-universe-domain                
          volumeMounts:
            {{- if .Values.php.medias.persistence.enabled }}
            - mountPath: /srv/app/public/media
              name: php-medias
            {{- end }}
            - mountPath: /var/run/php
              name: php-socket
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
          startupProbe:
            exec:
              command:
                - docker-healthcheck
            failureThreshold: 40
            periodSeconds: 3
          readinessProbe:
            exec:
              command:
                - docker-healthcheck
            periodSeconds: 3
          livenessProbe:
            exec:
              command:
                - docker-healthcheck
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources.php | nindent 12 }}
        {{- if .Values.consumer.enabled }}
        - name: {{ .Chart.Name }}-consumer
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          args: ['bin/console', 'messenger:consume']
          env:
            - name: API_ENTRYPOINT_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-host
            - name: JWT_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-jwt-passphrase
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-jwt-public-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-jwt-secret-key
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-trusted-proxies
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-app-env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-app-debug
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-app-secret
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-cors-allow-origin
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: database-url
            - name: MERCURE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mercure-url
            - name: MERCURE_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mercure-public-url
            - name: MERCURE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mercure-jwt-secret
          startupProbe:
            exec:
              command: ['pgrep', '-f', 'php bin/console messenger:consume']
            failureThreshold: 40
            periodSeconds: 3
          readinessProbe:
            exec:
              command: ['pgrep', '-f', 'php bin/console messenger:consume']
            periodSeconds: 3
          livenessProbe:
            exec:
              command: ['pgrep', '-f', 'php bin/console messenger:consume']
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources.consumer | nindent 12 }}
        {{- end }}
      volumes:
      {{- if .Values.php.medias.persistence.enabled }}
      - name: php-medias
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-php-medias-pvc
       {{- end }}
      - name: php-socket
        emptyDir: {}
      initContainers:
      {{- if .Values.php.medias.persistence.enabled }}
      - name: chown-mountpoint
        image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.php.image.pullPolicy }}
        securityContext:
          runAsUser: 0
        command:
        - sh
        - "-c"
        - |
          set -e
            echo "changing mountpoint ownership"
            chown www-data:www-data /srv/app/public/media/
        volumeMounts:
        - name: php-medias
          mountPath: /srv/app/public/media/
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
