apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bikelib.fullname" . }}-fixtures
  labels:
    {{- include "bikelib.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "bikelib.selectorLabelsFixtures" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bikelib.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-fixtures
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          command: ['/bin/sh', '-c']
          args: ['
            set -ex;
            if [ "$APP_ENV" != "prod" ]; then
              composer install --prefer-dist --no-progress --no-suggest --no-interaction;
            fi;
            bin/console -e test doctrine:database:drop --if-exists --force;
            bin/console -e test doctrine:database:create;
            bin/console -e test doctrine:migrations:migrate --no-interaction;
          ']
          env:
            - name: API_ENTRYPOINT_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-host
            - name: JWT_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-jwt-passphrase
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-jwt-public-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-jwt-secret-key
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-trusted-proxies
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-app-env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-app-debug
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-app-secret
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: php-cors-allow-origin
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: database-url
            - name: MERCURE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mercure-url
            - name: MERCURE_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mercure-public-url
            - name: MERCURE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "bikelib.fullname" . }}
                  key: mercure-jwt-secret
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
          startupProbe:
            exec:
              command:
                - docker-healthcheck
            failureThreshold: 40
            periodSeconds: 3
          readinessProbe:
            exec:
              command:
                - docker-healthcheck
            periodSeconds: 3
          livenessProbe:
            exec:
              command:
                - docker-healthcheck
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources.fixtures | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
