apiVersion: v1
kind: Service
metadata:
  name: {{ include "bikelib.fullname" . }}-pwa
  labels:
    {{- include "bikelib.labelsPWA" . | nindent 4 }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "bikelib.selectorLabelsPWA" . | nindent 4 }}
