apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustinelibre.fullname" . }}
  labels:
    {{- include "rustinelibre.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s-postgresql/%s?serverVersion=14&charset=utf8" .Values.postgresql.global.postgresql.auth.username .Values.postgresql.global.postgresql.auth.password .Release.Name .Values.postgresql.global.postgresql.auth.database | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{- end }}
  php-app-secret: {{ .Values.php.appSecret | default (randAlphaNum 40) | b64enc | quote }}
  php-jwt-passphrase: {{ .Values.php.jwt.passphrase | b64enc | quote }}
  php-jwt-public-key: {{ .Values.php.jwt.publicKey | b64enc | quote }}
  php-jwt-secret-key: {{ .Values.php.jwt.secretKey | b64enc | quote }}
  mercure-jwt-secret: {{ .Values.mercure.jwtSecret | default (randAlphaNum 40) | b64enc | quote }}
  {{- if .Values.maildev.enabled }}
  mailer-dsn: {{ printf "smtp://%s:%s" ( include "maildev.fullname" .Subcharts.maildev ) "1025" | b64enc | quote }}
  {{- else }}
  mailer-dsn: {{ .Values.mailer.dsn | b64enc | quote }}
  {{- end }}
  php-storage-key: {{ .Values.php.storage.key | b64enc | quote }}
  php-storage-secret: {{ .Values.php.storage.secret | b64enc | quote }}
  firebase-project-id: {{ .Values.php.firebase.projectID | b64enc | quote }}
  firebase-private-key-id: {{ .Values.php.firebase.privateKeyID | b64enc | quote }}
  firebase-private-key: {{ .Values.php.firebase.privateKey | quote }}
  firebase-client-email: {{ .Values.php.firebase.clientEmail | b64enc | quote }}
  firebase-client-id: {{ .Values.php.firebase.clientID | b64enc | quote }}
  firebase-auth-uri: {{ .Values.php.firebase.authUri | b64enc | quote }}
  firebase-token-uri: {{ .Values.php.firebase.tokenUri | b64enc | quote }}
  firebase-auth-provider: {{ .Values.php.firebase.authProvider | b64enc | quote }}
  firebase-client-cert-url: {{ .Values.php.firebase.clientCertUrl | b64enc | quote }}
  firebase-universe-domain: {{ .Values.php.firebase.universeDomain | b64enc | quote }}
