parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $mailerSender: "%env(MAILER_SENDER)%"
            string $webAppUrl: "%env(WEB_APP_URL)%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Employees\EventSubscriber\EmployeeSendPasswordEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\User\EventSubscriber\HashPasswordSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\User\EventSubscriber\ValidationCodeSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\Repairers\EventSubscriber\GpsPointEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\Repairers\EventSubscriber\SlugEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\Medias\EventSubscriber\RemoveFileEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\OpenApi\OpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@App\OpenApi\OpenApiFactory.inner' ]
        autoconfigure: false

    App\Tests\Resources\Services\Faker\DateTimeImmutableProvider: ~

    App\Tests\Resources\Services\Faker\AutoDiagnosticPrestationProvider: ~
