# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $mailerSender: "%env(MAILER_SENDER)%"
            string $webAppUrl: "%env(WEB_APP_URL)%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Employees\EventSubscriber\EmployeeSendPasswordEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\User\EventSubscriber\HashPasswordSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\Appointments\EventSubscriber\FirstSlotAvailableEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\Repairers\EventSubscriber\GpsPointEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\Repairers\EventSubscriber\RruleEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\OpenApi\OpenApiFactory:
        decorates: 'lexik_jwt_authentication.api_platform.openapi.factory'
        arguments: [ '@App\OpenApi\OpenApiFactory.inner' ]
        autoconfigure: false