{{- if .Values.dailyCronjobDbReset.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "bikelib-api.fullname" . }}-cronjob
  labels:
    {{- include "bikelib-api.labels" . | nindent 4 }}
spec:
  schedule: '0 0 * * *'
  jobTemplate:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "bikelib-api.selectorLabels" . | nindent 8 }}
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "bikelib-api.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}-cronjob
              image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.php.image.pullPolicy }}
              command: ['/bin/sh', '-c']
              args: ['
                set -ex;
                bin/console doctrine:schema:drop --full-database --force;
                bin/console doctrine:migrations:migrate --no-interaction;
              ']
              env:
                - name: API_ENTRYPOINT_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: php-host
                - name: JWT_PASSPHRASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: php-jwt-passphrase
                - name: JWT_PUBLIC_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: php-jwt-public-key
                - name: JWT_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: php-jwt-secret-key
                - name: TRUSTED_HOSTS
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: php-trusted-hosts
                - name: TRUSTED_PROXIES
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: php-trusted-proxies
                - name: APP_ENV
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: php-app-env
                - name: APP_DEBUG
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: php-app-debug
                - name: APP_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: php-app-secret
                - name: CORS_ALLOW_ORIGIN
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: php-cors-allow-origin
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: database-url
                - name: MERCURE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: mercure-url
                - name: MERCURE_PUBLIC_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: mercure-public-url
                - name: MERCURE_JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "bikelib-api.fullname" . }}
                      key: mercure-jwt-secret
              lifecycle:
                preStop:
                  exec:
                    command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
              startupProbe:
                exec:
                  command:
                    - docker-healthcheck
                failureThreshold: 40
                periodSeconds: 3
              readinessProbe:
                exec:
                  command:
                    - docker-healthcheck
                periodSeconds: 3
              livenessProbe:
                exec:
                  command:
                    - docker-healthcheck
                periodSeconds: 3
              resources:
                {{- toYaml .Values.resources.fixtures | nindent 16 }}
{{- end }}
