name: Build

on:
  workflow_call:

jobs:
  build-push-php:
    runs-on: ubuntu-latest
 
    steps:
    - name: Build/Push
      uses: coopTilleuls/action-docker-build-push@v6 
      with:
        IMAGE_NAME: bikelib-php
        BUILD_CONTEXT: api
        BUILD_TARGET: app_php
        REGISTRY_JSON_KEY: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_REPOSITORY: ghcr.io/cooptilleuls

  build-push-caddy:
    # Same Dockerfile as php, with a build target which is after
    needs: [build-push-php]
    runs-on: ubuntu-latest

    steps:
    - name: Build/Push
      uses: coopTilleuls/action-docker-build-push@v6
      with:
        IMAGE_NAME: bikelib-caddy
        BUILD_CONTEXT: api
        BUILD_TARGET: app_caddy
        REGISTRY_JSON_KEY: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_REPOSITORY: ghcr.io/cooptilleuls
       
  build-push-pwa:
    runs-on: ubuntu-latest
    steps:
    - name: Define Env
      run: |       
        set -o pipefail
        if [[ "${{ github.ref }}" == 'refs/heads/prod' ]]; then
            echo "SITE_KEY=${{ vars.PROD_CF_TURNSTILE_SITE_KEY }}" >> "$GITHUB_ENV"
        else
            echo "SITE_KEY=${{ vars.MAIN_CF_TURNSTILE_SITE_KEY }}" >> "$GITHUB_ENV"
        fi

    - name: Build/Push
      uses: coopTilleuls/action-docker-build-push@v7
      with:
        # BUILD_ARGS: NEXT_PUBLIC_CF_TURNSTILE_SITE_KEY=${{ env.SITE_KEY }}
        IMAGE_NAME: bikelib-pwa
        BUILD_CONTEXT: pwa
        BUILD_TARGET: prod
        REGISTRY_JSON_KEY: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_REPOSITORY: ghcr.io/cooptilleuls