name: Build

on:
  workflow_call:
    inputs:
      tags:
        type: string
        description: The Docker Tags (see docker/metadata-action@v4 for available values)
        required: true

jobs:
  build-push-php:
    runs-on: ubuntu-latest
 
    steps:
    - name: Build/Push
      uses: coopTilleuls/action-docker-build-push@v10
      with:
        IMAGE_NAME: bikelib-php
        BUILD_CONTEXT: api
        BUILD_TARGET: app_php
        REGISTRY_JSON_KEY: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_REPOSITORY: ghcr.io/cooptilleuls

  build-push-caddy:
    # Same Dockerfile as php, with a build target which is after
    needs: [build-push-php]
    runs-on: ubuntu-latest

    steps:
    - name: Build/Push
      uses: coopTilleuls/action-docker-build-push@v10
      with:
        IMAGE_NAME: bikelib-caddy
        BUILD_CONTEXT: api
        BUILD_TARGET: app_caddy
        REGISTRY_JSON_KEY: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_REPOSITORY: ghcr.io/cooptilleuls
       
  build-push-pwa:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.2
    - name: Login to registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io/cooptilleuls
        username: _json_key
        password: ${{ secrets.GITHUB_TOKEN }} 
    - name: Define Env
      run: |       
        set -o pipefail
        if [[ "${{ github.ref }}" == 'refs/heads/prod' ]]; then
            echo "SITE_KEY=${{ vars.PROD_CF_TURNSTILE_SITE_KEY }}" >> "$GITHUB_ENV"
        else
            echo "SITE_KEY=${{ vars.MAIN_CF_TURNSTILE_SITE_KEY }}" >> "$GITHUB_ENV"
        fi
    - name: Docker metadata
      id: docker-metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ vars.IMAGE_REPOSITORY_NAME }}/${{ vars.PWA_IMAGE_NAME }}
        tags: |
          type=raw,value=${{ github.sha }},priority=9999
          ${{ inputs.tags }}

    - name: Build and push
      uses: docker/build-push-action@v4    
      with:
        context: pwa
        target: prod
        pull: true
        push: true
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
        build-args: |
          NEXT_PUBLIC_CF_TURNSTILE_SITE_KEY=${{ env.SITE_KEY }}
          NEXT_PUBLIC_FIREBASE_API_KEY=${{ vars.FB_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ vars.FB_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ vars.FB_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ vars.FB_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ vars.FB_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID=${{ vars.FB_APP_ID }}
          NEXT_PUBLIC_VAPID_KEY=${{ vars.VAPID_KEY }}
        cache-from: type=registry,ref=${{ vars.IMAGE_REPOSITORY_NAME }}/${{ vars.PWA_IMAGE_NAME }}:buildcache

    # - name: Build/Push
    #   uses: coopTilleuls/action-docker-build-push@v10
    #   with:
    #     # BUILD_ARGS: NEXT_PUBLIC_CF_TURNSTILE_SITE_KEY=${{ env.SITE_KEY }}
    #     IMAGE_NAME: bikelib-pwa
    #     BUILD_CONTEXT: pwa
    #     BUILD_TARGET: prod
    #     REGISTRY_JSON_KEY: ${{ secrets.GITHUB_TOKEN }}
    #     IMAGE_REPOSITORY: ghcr.io/cooptilleuls
