name: CD


on:
  push:
    branches:
      - main
    tags: 
      - '*'
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]

jobs:
  remove-deploy-label:
    name: Remove deploy label
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - uses: mondeja/remove-labels-gh-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            deploy

  build:
    name: Build
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy'))
    uses: ./.github/workflows/build.yml
    with:
      tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=ref,event=tag
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=sha

  deploy:
    name: Deploy
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy'))
    needs: [ build ]
    uses: ./.github/workflows/deploy.yml
    concurrency: ${{ github.ref }}-deploy
    with:
      nonprod-storage-bucket: ${{ vars.NONPROD_STORAGE_BUCKET }}
      prod-storage-bucket: ${{ vars.PROD_STORAGE_BUCKET }}
    secrets:
      kubeconfig: ${{ secrets.KUBECONFIG }}
      domain: ${{ secrets.DOMAIN }}
      mailer-dsn: ${{ secrets.MAILER_DSN }}
      nonprod-storage-key: ${{ secrets.NONPROD_STORAGE_KEY }}
      nonprod-storage-secret: ${{ secrets.NONPROD_STORAGE_SECRET }}
      prod-storage-key: ${{ secrets.PROD_STORAGE_KEY }}
      prod-storage-secret: ${{ secrets.PROD_STORAGE_SECRET }}
      fb-project-id: ${{ secrets.FIREBASE_PROJECT_ID }}
      fb-private-key-id: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
      fb-private-key: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      fb-client-email: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      fb-client-id: ${{ secrets.FIREBASE_CLIENT_ID }}
      fb-auth-uri: ${{ secrets.FIREBASE_AUTH_URI }}
      fb-token-uri: ${{ secrets.FIREBASE_TOKEN_URI }}
      fb-auth-provider: ${{ secrets.FIREBASE_AUTH_PROVIDER }}
      fb-client-cert-url: ${{ secrets.FIREBASE_CLIENT_CERT_URL }}
      fb-universe-domain: ${{ secrets.FIREBASE_UNIVERSE_DOMAIN }}