name: CD


on:
  push:
    branches:
      - main
    tags: 
      - '*'
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]

jobs:
  remove-deploy-label:
    name: Remove deploy label
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - uses: mondeja/remove-labels-gh-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            deploy

  build:
    name: Build
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy'))
    uses: ./.github/workflows/build.yml
    with:
      tags: |
        type=ref,event=pr,prefix=pr-,priority=1000
        type=edge,branch=$repo.default_branch,priority=900
        type=raw,value=latest,enable={{is_default_branch}},priority=900 

  deploy:
    name: Deploy
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy'))
    needs: [ build ]
    uses: ./.github/workflows/deploy.yml
    concurrency: ${{ github.ref }}-deploy
    secrets:
      kubeconfig: ${{ secrets.KUBECONFIG }}
      domain: ${{ secrets.DOMAIN }}
      mailer-dsn: ${{ secrets.MAILER_DSN }}