name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-ci:
    name: API CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: app
          POSTGRES_PASSWORD: "!ChangeMe!"
          POSTGRES_USER: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: intl, apcu, json, zip
          ini-values: memory_limit=-1
          tools: pecl, composer, php-cs-fixer
          coverage: none
      - name: Get composer cache directory
        id: composercache
        run: echo "dir::$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Create env config
        run: |
          echo "DATABASE_URL=postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=15&charset=utf8" > .env.test.local
          cat .env.test.local
      - name: Install dependencies
        run: composer install
      - name: Test cs-fixer
        run: php vendor/bin/php-cs-fixer fix src --dry-run --diff --no-ansi
      - name: Static analysis
        run: php -d memory_limit=256M vendor/bin/psalm src
      - name: Tests
        run: php -d memory_limit=256M vendor/bin/phpunit
