name: Deploy PWA

on:
  workflow_call:
    secrets:
      kubeconfig:
        description: kubeconfig stored as a base64 encrypted secret
        required: true
    inputs:
      url:
        type: "string"
        description: URL used in deployment
        required: true 
      release_name:
        type: "string"
        description: Helm release name
        required: true
      context:
        type: "string"
        description: "Kube context (prod/nonprod)"
        required: true
      image_tag:
        type: "string"
        description: "Image tag"
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      URL: ${{ inputs.url }}
      CONTEXT: ${{ inputs.context }}
      RELEASE_NAME: ${{ inputs.release_name }}
      IMAGE_TAG: ${{ inputs.image_tag }}
    timeout-minutes: 15
    #permissions:
    #  contents: 'read'
    #  id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set kubeconfig
        run: |
          mkdir ~/.kube
          echo ${{ secrets.kubeconfig }} | base64 -d > ~/.kube/config
          kubectl config view

      # https://github.com/helm/helm/issues/8036
      - name: Build helm dependencies
        run: |
          set -o pipefail
          # add all repos
          if [ -f "./helm/pwa/Chart.lock" ]; then
            yq --indent 0 '.dependencies | map(["helm", "repo", "add", .name, .repository] | join(" ")) | .[]' "./helm/pwa/Chart.lock"  | sh --;
          fi
          helm dependency build ./helm/pwa

      - name: Deploy on namespace
        id: deploy

        run: |
          set -o pipefail
          helm upgrade --install ${RELEASE_NAME}-pwa ./helm/pwa \
            --atomic \
            --debug \
            --kube-context $CONTEXT \
            --values ./helm/pwa/values.yml \
            --values ./helm/pwa/values-prod.yml \
            --set=pwa.image.tag=${IMAGE_TAG} \
            --set=pwa.nextPublicEntrypoint=https://${RELEASE_NAME}-api-bikelib-api:80 \
          | sed --unbuffered '/USER-SUPPLIED VALUES/,$d'