name: Deploy

on:
  workflow_call:
    inputs:
      prod-storage-bucket:
        description: prod storage bucket name
        required: true
        type: string
      nonprod-storage-bucket:
        description: nonprod storage bucket name
        required: true
        type: string
    secrets:
      kubeconfig:
        description: kubeconfig stored as a base64 encrypted secret
        required: true
      domain:
        description: Main project deploy domain used in URLs
        required: true
      mailer-dsn:
          description: MAILER DSN
      nonprod-storage-key:
        description: nonprod storage key
        required: true
      nonprod-storage-secret:
        description: nonprod storage secret
        required: true
      prod-storage-key:
        description: prod storage key
        required: true
      prod-storage-secret:
        description: prod storage secret
        required: true
      fb-project-id:
        required: true
      fb-private-key-id:
        required: true
      fb-private-key:
        required: true
      fb-client-email:
        required: true
      fb-client-id:
        required: true
      fb-auth-uri:
        required: true
      fb-token-uri:
        required: true
      fb-auth-provider:
        required: true
      fb-client-cert-url:
        required: true
      fb-universe-domain:
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PROD_STORAGE_BUCKET: ${{ inputs.prod-storage-bucket }}
      NONPROD_STORAGE_BUCKET: ${{ inputs.nonprod-storage-bucket }}
    #permissions:
    #  contents: 'read'
    #  id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set kubeconfig
        run: |
          mkdir ~/.kube
          echo ${{ secrets.kubeconfig }} | base64 -d > ~/.kube/config
          kubectl config view

      # https://github.com/helm/helm/issues/8036
      - name: Build helm dependencies
        run: |
          set -o pipefail
          # add all repos
          if [ -f "./helm/chart/Chart.lock" ]; then
            yq --indent 0 '.dependencies | map(["helm", "repo", "add", .name, .repository] | join(" ")) | .[]' "./helm/chart/Chart.lock"  | sh --;
          fi
          helm dependency build ./helm/chart

      - name: Deploy on namespace
        id: deploy
        run: |
          set -o pipefail
          if [[ "${{ github.ref }}" == *"tag"* ]]; then
              # Tags are deployed in prod
              CONTEXT=prod
              IMAGE_TAG=${{ github.ref_name }}
              RELEASE_NAME=demo             
              URL=demo.${{ secrets.domain }};
              STORAGE_NAME=${PROD_STORAGE_BUCKET}
              STORAGE_KEY=${{ secrets.prod-storage-key }}
              STORAGE_SECRET=${{ secrets.prod-storage-secret }}
          else
              CONTEXT=nonprod
              IMAGE_TAG=sha-${GITHUB_SHA::7}
              STORAGE_KEY=${{ secrets.nonprod-storage-key }}
              STORAGE_SECRET=${{ secrets.nonprod-storage-secret }}
              STORAGE_NAME=${NONPROD_STORAGE_BUCKET}
              if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
                  RELEASE_NAME=pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
              else
                  RELEASE_NAME=${{ github.ref_name }}
              fi
              URL=${RELEASE_NAME}.nonprod.${{ secrets.domain }}
          fi
          export APP_APP_JWT_PUBLIC_KEY=$(openssl rand -base64 32)
          export APP_JWT_PASSPHRASE=$(openssl rand -base64 32)
          export APP_JWT_SECRET_KEY=$(openssl genpkey -pass file:<(echo "$APP_APP_JWT_PUBLIC_KEY") -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096)
          export APP_JWT_PUBLIC_KEY=$(openssl pkey -in <(echo "$APP_JWT_SECRET_KEY") -passin file:<(echo "$APP_APP_JWT_PUBLIC_KEY") -pubout)
          export TRUSTED_HOSTS="^127.0.0.1|localhost|${URL}|${RELEASE_NAME}-bikelib$"
          export MERCURE_JWT_PUBLIC_KEY=$(openssl genpkey -pass file:<(echo "$APP_JWT_PASSPHRASE") -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096)
          export MERCURE_EXTRA_DIRECTIVES=$(cat <<EOF
          cors_origins http://localhost:8080 http://localhost:8081 https://localhost http://localhost https://${URL}
          EOF
          )
          helm upgrade --install $RELEASE_NAME ./helm/chart \
            --atomic \
            --debug \
            --kube-context $CONTEXT \
            --set=php.image.tag=${IMAGE_TAG} \
            --set=caddy.image.tag=${IMAGE_TAG} \
            --set=pwa.image.tag=${IMAGE_TAG} \
            --set=ingress.hosts[0].host=${URL} \
            --set=ingress.tls[0].secretName=${RELEASE_NAME}-tls \
            --set=ingress.tls[0].hosts[0]=${URL} \
            --set=php.corsAllowOrigin="https?://.*?\.${URL}$" \
            --set=mailer.dsn='${{ secrets.mailer-dsn }}' \
            --set=php.corsAllowOrigin="https?://${URL}$" \
            --set=php.trustedHosts="${TRUSTED_HOSTS//./\\\\.}" \
            --set=php.jwt.secretKey="${APP_JWT_SECRET_KEY}" \
            --set=php.jwt.publicKey="${APP_JWT_PUBLIC_KEY}" \
            --set=php.jwt.passphrase=${APP_APP_JWT_PUBLIC_KEY} \
            --set=php.host=https://${URL} \
            --set=mercure.publicUrl=https://${URL}/.well-known/mercure \
            --set=mercure.jwtSecret="${MERCURE_JWT_PUBLIC_KEY}" \
            --set=mercure.extraDirectives="${MERCURE_EXTRA_DIRECTIVES}" \
            --set=php.storage.bucket="${STORAGE_NAME}" \
            --set=php.storage.endpoint="https://storage.googleapis.com" \
            --set=php.storage.region="eu-west-1" \
            --set=php.storage.usePathStyleEndpoint=true \
            --set=php.storage.key="${STORAGE_KEY}" \
            --set=php.storage.secret="${STORAGE_SECRET}" \
            --set=php.firebase.projectID="${{ secrets.fb-project-id }}" \
            --set=php.firebase.privateKeyID="${{ secrets.fb-private-key-id }}" \
            --set=php.firebase.privateKey="${{ secrets.fb-private-key }}" \
            --set=php.firebase.clientEmail="${{ secrets.fb-client-email }}" \
            --set=php.firebase.clientID="${{ secrets.fb-client-id }}" \
            --set=php.firebase.authUri="${{ secrets.fb-auth-uri }}" \
            --set=php.firebase.tokenUri="${{ secrets.fb-token-uri }}" \
            --set=php.firebase.authProvider="${{ secrets.fb-auth-provider }}" \
            --set=php.firebase.clientCertUrl="${{ secrets.fb-client-cert-url }}" \
            --set=php.firebase.universeDomain="${{ secrets.fb-universe-domain }}" \
            --values ./helm/chart/values.yml \
            --values ./helm/chart/values-prod.yml \
            | sed --unbuffered '/USER-SUPPLIED VALUES/,$d'
          echo "URL=$URL" >> $GITHUB_OUTPUT

      - name: Output deployment URL
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          URL: ${{ steps.deploy.outputs.URL }}
        with:
          script: |
            const { URL } = process.env
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Chart has been deployed with this url:\n\`\`\`\n${URL}\n\`\`\``
            })
